apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: mysql_master
      name: mysql_master
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: 12345
        - name: MYSQL_REPLICATION_PASSWORD
          value: 12345
      ports: 
        - containerPort: 3306
          name: mysql

