apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels: 
    name: wordpress
spec: 
  containers: 
    - image: wordpress
      name: wordpress
      env:
        - name: WORDPRESS_DB_PASSWORD
          # change this - must match mysql.yaml password
          value: 12345
	- name: WORDPRESS_DB_USER
	  value: root
	- name: WORDPRESS_DB_HOST
	  value: mysql_master
      ports: 
        - containerPort: 80
          name: wordpress


